Repository localcontexts/localcontextshub, pull requests merged in 2024-04, with the labels that each got.

#142 #86881gvyw Added inactive users modal
  accounts/migrations/0020_inactiveuser.py
  accounts/models.py
  accounts/signals.py
  helpers/scheduler.py
  localcontexts/admin.py
Labels: enhancement

#118 #8687dntxz Added subscription forms and templates for journeys
  accounts/forms.py
  accounts/urls.py
  accounts/utils.py
  accounts/views.py
  env.sh-example
  helpers/utils.py
  institutions/decorators.py
  institutions/migrations/0032_institution_is_subscribed.py
  institutions/models.py
  institutions/urls.py
  institutions/utils.py
  institutions/views.py
  localcontexts/settings.py
  localcontexts/static/css/main.css
  localcontexts/static/javascript/main.js
  projects/migrations/0191_alter_project_project_privacy_and_more.py
  templates/accounts/dashboard.html
  templates/accounts/login.html
  templates/accounts/subscription-inquiry.html
  templates/institutions/confirm-subscription-institution.html
  templates/partials/headers/header-content.html
  templates/partials/infocards/_institution-card.html
  templates/register-base.html
Labels: New Feature

#111 #8685dweqe Notification-for-Notified-Communities
  helpers/emails.py
  helpers/utils.py
  researchers/views.py
Labels: enhancement

#147 #8687ypkg0 View Label: return 404 instead of 500 if Label does not exist
  communities/views.py
Labels: bug

#150 #8687ypjdr Should not be able to save a Label if default text is empty
  bclabels/forms.py
  communities/views.py
  templates/communities/select-label.html
  templates/partials/_add-translation.html
  tklabels/forms.py
Labels: bug

#152 #86879gwuc Download Labels button help text floating away
  localcontexts/static/css/main.css
Labels: bug

#159 #86886vqv4 Corrected admin invite role
  templates/accounts/member-invitations.html
Labels: bug

#161 #86884c9ff Hyperlink not opening in embeds when clicked
  localcontexts/static/javascript/main.js
  templates/accounts/embed-notice.html
  templates/projects/embed-project.html
Labels: bug

#166 #868893z1n create project error
  institutions/views.py
Labels: bug

#158 #86886tz8p Address feedback on subscription tickets
  accounts/models.py
  accounts/views.py
  api/versioned/v2/views.py
  communities/forms.py
  communities/migrations/0051_alter_invitemember_role.py
  communities/models.py
  helpers/utils.py
  institutions/decorators.py
  institutions/migrations/0033_institution_is_submitted.py
  institutions/models.py
  institutions/utils.py
  institutions/views.py
  localcontexts/static/css/main.css
  localcontexts/static/javascript/main.js
  templates/account_settings_pages/_api-keys.html
  templates/accounts/member-invitations.html
  templates/partials/_member-requests.html
  templates/partials/_members.html
  templates/partials/_notices.html
  templates/partials/_project-actions.html
  templates/partials/infocards/_institution-card.html
  templates/projects/projects.html
Labels: bug
